### ISSUE TITLE
Adding XML linting

### ISSUE THREAD

**Issue by willlordarm** [Open-CMSIS-Pack/SW-Pack-HandsOn#1]
In the most recent CMSIS WG call it was mentioned that XML linting isn't covered yet. I think this should be fairly trivial to add using an [existing marketplace GH Action](https://github.com/marketplace/actions/xml-lint). 

Here's an example of a workflow I created a while back to lint PDSCs against the schema.

```xml
name: PDSC XML Lint

on:
  push:
    paths:
      - '**.pdsc'

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download schema
      run: wget https://raw.githubusercontent.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/main/schema/PACK.xsd
    - name: Lint PDSC
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: '**.pdsc'
        xml-schema-file: ./PACK.xsd
```

**Comment by ReinhardKeil** [comment]
Thanks for raising this issue.  XML Lint is covered already (by similar concepts), but not directly integrated in `packchk`. So the statement was about `packchk` not about XML Lint (XML Lint is already part of the gen_pack process).

**Comment by jkrech** [comment]
here xmllint is called as part of the `gen_pack`
https://github.com/Open-CMSIS-Pack/gen-pack 
see: https://github.com/Open-CMSIS-Pack/gen-pack#xmllint for local setup
Here the machine setup installs xmllint for the github action:
https://github.com/Open-CMSIS-Pack/gen-pack-action

For completeness:
This version of packchk starts to do the xml schema check unconditionally 
https://github.com/Open-CMSIS-Pack/devtools/releases/tag/tools%2Fpackchk%2F1.3.99
However we still need to fix a blocking bug and we want to add a copy of the  PACK.xsd in the `./etc` directory of CMSIS-Toolbox which is used by default for validating the pdsc schema.

This will simplify the usage.
